config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  # devise_for :users, controllers: { confirmations: 'confirmations', registrations: 'registrations' }
  
  resources :crashes
  resources :reviews
  resources :students
  root to: "application#index"

  get '/students/:id/info', to: 'students#info', as: 'student_info'

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user, class_name: 'User', foreign_key: :devise_id
  has_many :hosted_crashes, class_name: 'Crash', foreign_key: :host_id
  has_many :crashes, foreign_key: :crasher_id
  has_many :reviews_written, foreign_key: :reviewer_id
  has_many :reviews, foreign_key: :reviewee_id

  def full_name
    first_name + ' ' + last_name
  end

  def unreviewed_crashes
    crashes = self.hosted_crashes.map do |crash|
      crash if crash.reviews.length == 0
    end
    crashes.compact
  end

  def average_crasher_rating
    reviews = all_crasher_reviews
    total_score = reviews.inject (0) {|sum, review| sum + review.rating}
    (total_score / reviews.count).round(2)
  end

  def average_host_rating
    reviews = all_host_reviews
    total_score = reviews.inject (0) {|sum, review| sum + review.rating}
    (total_score / reviews.count).round(2)
  end

  private
  
  def all_crasher_reviews
    reviews.select do |review| 
      review.crash.crasher_id == self.id
    end
  end

  def all_host_reviews
    reviews.select do |review| 
      review.crash.host_id == self.id
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :info]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    @students.as_json
  end

  def info
    
  end

  # GET /students/1
  # GET /students/1.json
  def show
    if current_user.id != @student.id
      redirect_to student_path(current_user.id)
    else
      @crashes = Crash.where(crasher_id: current_user.id)
      @requested_crashes = Crash.where(crasher_id: current_user.id, accepted: false)
      @hostings = Crash.where(host_id: current_user.id, accepted: true)
      @pending_hostings = Crash.where(host_id: current_user.id, accepted: false)
      @potential_crashes = Student.where(hosting_zip: @student.zip, is_host: true, crashable: true)
      if @student.is_host
        @unrated_crashes = @student.unreviewed_crashes
      end
    end
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :devise_id, :is_crasher, :is_host, :school, :crashable, :zip, :crashable_type)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h3>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, autofocus: true %>
  </div>
    <%= hidden_field_tag 'student[devise_id]', current_user.id %>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.check_box :is_crasher %>
    <%= f.label :is_crasher %><br>
  </div>
  <div class="field">
    <%= f.check_box :is_host %>
    <%= f.label :is_host %><br>
  </div>
  <div class="field">
    <%= f.label :crashable_type, 'If you are a host, what sleeping arrangement do you have to offer? (ex \'bedroom\', \'Couch\' etc)' %><br>
    <%= f.text_field :crashable_type %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :zip, "Zip Code where you usually Crash" %><br>
    <%= f.number_field :zip %>
  </div>
    <div class="field">
    <%= f.label :hosting_zip, "If you're a host, input the zipcode where you intend to host" %><br>
    <%= f.number_field :hosting_zip %>
  </div>
  <div class="actions">
    <%= f.submit "Create Student", class: "cyan accent-2 waves-effect waves-light btn black-text"  %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h3>Editing Student</h3>

<%= render 'form' %>

<%= link_to 'Back', @student %> | 
<%= link_to('Edit Registration Info', edit_user_registration_path) %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Students</h3>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Devise</th>
      <th>Is crasher</th>
      <th>Is host</th>
      <th>School</th>
      <th>Crashable?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.devise_id %></td>
        <td><%= student.is_crasher %></td>
        <td><%= student.is_host %></td>
        <td><%= student.school %></td>
        <td><%= student.crashable? %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/info.html.erb
<h3>User: <%= @student.full_name %></h3>

<table>
  <thead>
    <tr>
      <th>Number of Crashes</th>
      <th>Rating</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @student.crashes.count %></td>
      <td><%= @student.average_crasher_rating %></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to "Back", student_path(current_user) %>

app/views/students/new.html.erb
<h3>Profile Information</h3>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<div class='left-panel'>
  <% if @student.is_host %>
    <h3>Is your <%= @student.crashable_type %> available?</h3>
    <%= form_for(@student) do |f| %>
      <div class="field">
        <%= f.check_box :crashable, class: "cyan accent-2" %>
        <%= f.label :crashable, "#{@student.crashable_type} Available?"%><br>
      </div>
      <div class="actions">
        <%= f.submit "Update Availability", class: "cyan accent-2 waves-effect btn black-text" %>
      </div>
    <% end %>
    <% if @unrated_crashes != [] %>
      <h3>Unrated Crashes</h3>
      <p>Please rate your experience with the following crashers:</p>
      <% @unrated_crashes.each do |crash| %>
        <ul>
          <li><%= crash.crasher.full_name %> crashed at your place on <%= crash.date.strftime('%x') %></li>
          <li>They offered you the following: <%= crash.item_for_exchange %></li>
          <li><%= link_to 'Click here to review this crash', new_review_path(crash: crash.id)%> </li>
        </ul>
      <% end %>
    <% end %>
  <% end %>

  <h3>Places to stay in <%= @student.zip %></h3>
  <% if @potential_crashes %>
    <ul>
      <% @potential_crashes.each do |host| %>
        <li><%= host.first_name %> has a <%= host.crashable_type %> in <%= @student.zip %>! <%= link_to 'Click here to find out more!', new_crash_path(host_id: host.id) %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No Potential crashes in your area! Invite your friends or search a new area!</p>
  <% end %>
  <h4>Search a different Zip Code</h4>
  <%= form_for(@student) do |f| %>
      <div class="field">
        <%= f.label :zip, "Enter Zip Code below"%><br>
        <%= f.number_field :zip %>
      </div>
      <div class="actions">
        <%= f.submit "Search", class: "cyan accent-2 waves-effect btn black-text" %>
      </div>
  <% end %>
</div>
<div class="right-panel">
<%= render partial: "/crashes/crash_listings", locals: { crashes: @crashes, requested_crashes: @requested_crashes, hostings: @hostings, pending_hostings: @pending_hostings, errors: @errors } %>
</div>
<footer>
<%= link_to 'Back', root_path %>
</footer>