config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  # devise_for :users, controllers: { confirmations: 'confirmations', registrations: 'registrations' }
  
  resources :crashes
  resources :reviews
  resources :students
  root to: "application#index"

  get '/students/:id/info', to: 'students#info', as: 'student_info'

end

app/models/crash.rb
class Crash < ActiveRecord::Base
  belongs_to :host, class_name: 'Student', foreign_key: :host_id
  belongs_to :crasher, class_name: 'Student', foreign_key: :crasher_id
  has_many :reviews
end

app/controllers/crashes_controller.rb
class CrashesController < ApplicationController
  before_action :set_crash, only: [:show, :edit, :update, :destroy]

  # GET /crashes
  # GET /crashes.json
  def index
    # @crashes = Crash.where(crasher_id: current_user.id)
    # @requested_crashes = Crash.where(crasher_id: current_user.id, accepted: false)
    # @hostings = Crash.where(host_id: current_user.id, accepted: true)
    # @pending_hostings = Crash.where(host_id: current_user.id, accepted: false)
    redirect_to current_user.student
  end

  # GET /crashes/1
  # GET /crashes/1.json
  def show
    @crash = Crash.find(params[:id])
  end

  # GET /crashes/new
  def new
    @host = Student.find(params[:host_id])
    @crash = Crash.new
  end

  # GET /crashes/1/edit
  def edit
  end

  # POST /crashes
  # POST /crashes.json
  def create
    @crash = Crash.new(crash_params)

    respond_to do |format|
      if @crash.save
        format.html { redirect_to @crash, notice: 'Crash was successfully created.' }
        format.json { render :show, status: :created, location: @crash }
      else
        format.html { render :new }
        format.json { render json: @crash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crashes/1
  # PATCH/PUT /crashes/1.json
  def update
    if params[:crash][:accepted]
      @crash.update_attributes(accepted: params[:crash][:accepted])
    end
    respond_to do |format|
      if @crash.update(crash_params)
        format.html { redirect_to crashes_path, notice: 'Crash was successfully updated.' }
        format.json { render :show, status: :ok, location: @crash }
      else
        format.html { render :edit }
        format.json { render json: @crash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crashes/1
  # DELETE /crashes/1.json
  def destroy
    @crash.destroy
    respond_to do |format|
      format.html { redirect_to crashes_url, notice: 'Your request was successfully canceled.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crash
      @crash = Crash.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crash_params
      params.require(:crash).permit(:date, :item_for_exchange, :host_id, :crasher_id)
    end
end

app/helpers/crashes_helper.rb
module CrashesHelper

  
  
end

app/views/crashes/_crash_listings.html.erb
<% if !pending_hostings.empty? %>
  <h3>Hosting Opportunities</h3>
  <p>Ready to host? Review these crashers who've requested to be your guest.</p>

  <table>
    <thead>
      <tr>
        <th>Crasher</th>
        <th>Date</th>
        <th>Crasher Offer</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% pending_hostings.each do |hosting| %>
        <tr>
          <td><%= link_to hosting.crasher.full_name, crash_path(hosting) %></td>
          <td><%= hosting.date %></td>
          <td><%= hosting.item_for_exchange %></td>
          <td><%= link_to 'Accept', crash_path(hosting, crash: {accepted: true}), :method => :put %></td>
          <td><%= link_to 'Decline', crash_path(hosting, crash: {accepted: false}), :method => :put %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if !requested_crashes.empty? %>
  <h3>Your Pending Crashes</h3>

  <p>Hang tight. These crash requests have yet to be reviewed by their host.</p>

  <table>
    <thead>
      <tr>
        <th>Host</th>
        <th>Date</th>
        <th>Crasher Offer</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% requested_crashes.each do |crash| %>
        <tr>
          <td><%= link_to crash.host.full_name, crash_path(crash) %></td>
          <td><%= crash.date %></td>
          <td><%= crash.item_for_exchange %></td>
          <td><%= link_to 'Cancel Request', crash, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if !crashes.empty? %>
  <h3>Your Upcoming Crashes</h3>

  <table>
    <thead>
      <tr>
        <th>Host</th>
        <th>Date</th>
        <th>Your Exchange</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% crashes.each do |crash| %>
        <tr>
          <td><%= link_to crash.host.full_name, crash_path(crash) %></td>
          <td><%= crash.date %></td>
          <td><%= crash.item_for_exchange %></td>
          <td><%= link_to 'Cancel Crash', crash, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<% if !hostings.empty? %>

  <h3>Your Upcoming Hostings</h3>

  <table>
    <thead>
      <tr>
        <th>Crasher</th>
        <th>Date</th>
        <th>Crasher Offer</th>
      </tr>
    </thead>

    <tbody>
      <% hostings.each do |hosting| %>
        <tr>
          <td><%= link_to hosting.crasher.full_name, crash_path(hosting) %></td>
          <td><%= hosting.date %></td>
          <td><%= hosting.item_for_exchange %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
 <% end %>

app/views/crashes/_form.html.erb
<%= form_for(@crash) do |f| %>
  <% if @crash.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@crash.errors.count, "error") %> prohibited this crash from being saved:</h3>

      <ul>
      <% @crash.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date, :class => 'datepicker' %>
  </div>
  <div class="field">
    <%= f.label :item_for_exchange %><br>
    <%= f.text_field :item_for_exchange %>
  </div>
  <div class="field">    
    <%= f.hidden_field :host_id, value: @host.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :crasher_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crashes/edit.html.erb
<h3>Editing Crash</h3>

<%= render 'form' %>

<%= link_to 'Show', @crash %> |
<%= link_to 'Back', crashes_path %>

app/views/crashes/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Profile Page</h3>

<%= render partial: "/crashes/crash_listings", locals: { crashes: @crashes, requested_crashes: @requested_crashes, hostings: @hostings, pending_hostings: @pending_hostings, errors: @errors } %>

<br>
<%= link_to 'New Crash', new_crash_path %>
<br>

app/views/crashes/new.html.erb
<h3>New Crash</h3>

<%= render 'form' %>

<%= link_to 'Back', crashes_path %>

app/views/crashes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @crash.date %>
</p>

<p>
  <strong>Item for exchange:</strong>
  <%= @crash.item_for_exchange %>
</p>

<p>
  <strong>Host:</strong>
  <%= @crash.host.full_name %> 
  <% if @crash.host_id != current_user.id %>
    (<%= link_to "View Profile", student_info_path(@crash.host) %>)
  <% end %>
</p>

<p>
  <strong>Crasher:</strong>
  <%= @crash.crasher.full_name %> 
  <% if @crash.crasher_id != current_user.id %>
    (<%= link_to "View Profile", student_info_path(@crash.crasher) %>)
  <% end %>
</p>

<%= link_to 'Back', student_path(current_user.student) %>