config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  # devise_for :users, controllers: { confirmations: 'confirmations', registrations: 'registrations' }
  
  resources :crashes
  resources :reviews
  resources :students
  root to: "application#index"

  get '/students/:id/info', to: 'students#info', as: 'student_info'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new(crash_id: params[:crash].to_i)
    @crash = Crash.find(params[:crash].to_i)
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.assign_attributes(reviewer_id: current_user.id, reviewee_id: assign_reviewee)
    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:crash_id, :review_id, :review_text, :rating)
    end

    def assign_reviewee
      if current_user.id == crash.host_id
        return crash.crasher_id
      elsif current_user.id == crash.crasher_id
        return crash.host_id
      end
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :crash_id %>

  <div class="field">
    <%= f.label :rating, "How would you rate #{@crash.crasher.first_name} as a guest?" %><br>
    <%= f.number_field :rating , max: 5%>(out of 5)
  </div>
  <div class="field">
    <%= f.label :review_text, "Tell us some more about #{@crash.crasher.first_name}\'s stay." %><br>
    <%= f.text_area :review_text, rows: 15, cols: 50 %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h3>Editing Review</h3>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Reviews</h3>

<table>
  <thead>
    <tr>
      <th>Crash</th>
      <th>Review</th>
      <th>Review text</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.crash_id %></td>
        <td><%= review.review_id %></td>
        <td><%= review.review_text %></td>
        <td><%= review.rating %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h3>Review for Crash on <%= @crash.date.strftime('%x') %> </h3>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Crash Date:</strong>
  <%= @review.crash.date.strftime('%x') %>
</p>

<p>
  <strong>Crasher Name:</strong>
  <%= @review.crash.crasher.full_name %>
</p>

<p>
  <strong>Review text:</strong>
  <%= @review.review_text %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>